# Header Menu
menu:
  Home: /
  Products: /products/
  # Blog: /archives/ # can set archive-dir in root config to custom value
  Contact: /contact/
  About: /about/
   
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 

# Social
social:
  # github: https://github.com/ptsteadman
  # twitter: https://twitter.com/ptsteadman
  # facebook: https://www.facebook.com/ptsteadman
  # rss: atom.xml
  # linkedin: https://linkedin.com/in/ptsteadman
  # stackoverflow: http://stackoverflow.com/users/2480493/patrick-steadman

# Miscellaneous
color_scheme: green   # options: blue, gray, green, orange, red, turquoise
# favicon: /favicon.ico # path from root of hexo site
# twitter_widget_id: "678830341331820544" # as a string, from https://twitter.com/settings/widgets
# twitter_username: computerlab_ # twitter username without the @
default_author: Anonymous

about: MAOJI IMP. & EXP. LIMITED is a professional trading company with own factory in China and partner factories in Europe, USA and South America, mainly dealing with feed ingredients, feed additives and pet food.
# phone: 716-472-4484
email: office@maojigroup.com
address_1: JINSHAN BUILDING ROOM 1703
address_2: CHANGSHOU SOUTH ROAD 555#
address_3: NINGBO, 315100, CHINA
# skype: ptsteadman
# lat: 40.715911 
# long: -73.962147
